# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RIFunctionCollection' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RIFunctionCollection
  pod  'SDWebImage'
  pod "AFNetworking"
  pod "SVProgressHUD"
  pod "MJRefresh"
  pod "SDAutoLayout"
  pod 'Bugly'
  pod 'FMDB/SQLCipher'
  pod 'SSZipArchive'
  pod 'FMDB/SQLCipher'
end
